name: "engine"

services:
    engine:
        build:
            context: ../..
            dockerfile: ./apps/engine/Dockerfile
            target: build
        ports:
            - "4200:4200"
        volumes:
            - .:/app/apps/engine
            - ../../libs/database/dist:/app/libs/database/dist
            - ../../libs/sdk/dist:/app/libs/sdk/dist
        env_file:
            - .env
        command: npm run --workspace apps/engine dev
        depends_on:
            postgres:
                condition: service_healthy
            lib-database-build:
                condition: service_completed_successfully
            lib-sdk-build:
                condition: service_completed_successfully
